// https://docs.expo.dev/versions/v57.0.0/ → "Using ESLint" (generated by `npx expo lint`).
const { defineConfig, globalIgnores } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const globals = require('globals');

module.exports = defineConfig([
  globalIgnores([
    'node_modules/**',
    'ios/**',
    'android/**',
    'dist/**',
    '.expo/**',
    'coverage/**',
    'docs/**',
    'certs/**',
    // Generated from the Figma icon set; not hand-edited.
    'components/iconRegistry.js',
  ]),
  expoConfig,
  {
    rules: {
      // React Compiler checks. The compiler is not enabled, and the app leans on
      // patterns it forbids on purpose (a `latest.current = state` ref mirror
      // for timers, a module singleton written during render for routing guards).
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/globals': 'off',
    },
  },
  {
    files: ['**/__tests__/**', '**/*.test.js', 'jest.setup.js', 'test/**', 'store/testing.js'],
    languageOptions: { globals: { ...globals.jest, ...globals.node } },
    rules: {
      // Imports after jest.mock(...) read in the order they take effect; babel-jest
      // hoists the mocks either way.
      'import/first': 'off',
      // Mock factories return anonymous stand-in components.
      'react/display-name': 'off',
    },
  },
  {
    files: ['scripts/**', 'plugins/**', 'eslint.config.js'],
    languageOptions: { globals: globals.node },
  },
]);
